version: '{build}'
image: Visual Studio 2017

platform:
#    - Win32
#    - x64
    - ARM
#    - ARM64

configuration:
    - Release

before_build:
    - cmake . -G "Visual Studio 15 2017" -A %PLATFORM%

build_script:
    - cmake --build . --config %CONFIGURATION%

after_build:
    - cmake --build . --target package --config %CONFIGURATION%

artifacts:
    - path: wdd-*.zip
